info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
spring:
  application:
    name: "@project.artifactId@"
endpoints:
  enabled: true
logging:
  level:
    root: WARN
    net:
      starkenberg: DEBUG
app:
  repo:
    log:
      days: 7	
      host: "server"
      port: 9200
      indexPrefixs: "logstash-"
      indexDateFormat: "yyyy.MM.dd"
      deleteCronExpression: "0 23 7 * * *"
      createCronExpression: "0 15 21 * * *"